SELECT QI.SABOR, QI.ANO, QI.QUANTIDADE FROM (
SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO,
sum(INF.QUANTIDADE) AS QUANTIDADE
FROM tabela_de_produtos AS TP
INNER JOIN itens_notas_fiscais AS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais AS NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY QUANTIDADE DESC) AS QI;

SELECT QT.ANO, QT.QUANTIDADE FROM (
SELECT YEAR(NF.DATA_VENDA) AS ANO,
sum(INF.QUANTIDADE) AS QUANTIDADE
FROM tabela_de_produtos AS TP
INNER JOIN itens_notas_fiscais AS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais AS NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA)
ORDER BY QUANTIDADE DESC) AS QT;







